
class ProductService{
    static productlist:any=[
        {
            id: "1",
            src: require("../assets/img/ecommerce/1.jpg"),
            num: "(23)",
            name: "women party wear dress",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$2,498",
            prices: "$1,967",
            price: 1967,
            Size: "Size",
            XXL: "XXL",
            bg: "Color :",
            colors: "Red color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
        {
            id: "2",
            src: require("../assets/img/ecommerce/2.jpg"),
            num: "(64)",
            name: "White Ear buds",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$2,999",
            prices: "$1,999",
            price: 1999,
            Size: "Size",
            XXL: "S",
            bg: "Color :",
            colors: "white color",
            stock: "Out of stock",
            stockbg: "danger",
            qnty: 2,
        },
        {
            id: "3",
            src: require("../assets/img/ecommerce/3.jpg"),
            num: "(41)",
            name: "simple white Chair",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$1,499",
            prices: "$999",
            price: 999,
            Size: "Size",
            XXL: "M",
            bg: "Color :",
            colors: "simple white color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
        {
            id: "4",
            src: require("../assets/img/ecommerce/4.jpg"),
            num: "(232)",
            name: "pink teddy bear",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$498",
            prices: "$225",
            price: 225,
            Size: "Size",
            XXL: "L",
            bg: "Color :",
            colors: "Sky blue color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
        {
            id: "5",
            src: require("../assets/img/ecommerce/5.jpg"),
            num: "(143)",
            name: "Lence Camara",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$298",
            prices: "$198",
            price: 198,
            Size: "Size",
            XXL: "XXL",
            bg: "Color :",
            colors: "black color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
        {
            id: "6",
            src: require("../assets/img/ecommerce/06.jpg"),
            num: "(29)",
            name: "Glass with soil gift item",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$2,999",
            prices: "$2,499",
            price: 2499,
            Size: "Size",
            XXL: "XL",
            bg: "Color :",
            colors: "Red color",
            stock: "Out of stock",
            stockbg: "danger",
            qnty: 1,
        },
        {
            id: "7",
            src: require("../assets/img/ecommerce/9.jpg"),
            num: "(20)",
            name: "Glass Flower pot",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$3,498",
            prices: "$2,999",
            price: 2999,
            Size: "Size",
            XXL: "S",
            bg: "Color :",
            colors: "pink color",
            stock: "In stock",
            stockbg: "success",
            qnty: 3,
        },
        {
            id: "8",
            src: require("../assets/img/ecommerce/8.jpg"),
            num: "(283)",
            name: "Mens party wear t-shirt",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$2,498",
            prices: "$1,967",
            price: 1967,
            Size: "Size",
            XXL: "XXL",
            bg: "Color :",
            colors: "gray color",
            stock: "In stock",
            stockbg: "success",
            qnty: 5,
        },
        {
            id: "9",
            src: require("../assets/img/ecommerce/9.jpg"),
            num: "(14)",
            name: "Glass Flower pot",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$1,499",
            prices: "$1,299",
            price: 1299,
            Size: "Size",
            XXL: "XXL",
            bg: "Color :",
            colors: "Red color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
        {
            id: "10",
            src: require("../assets/img/ecommerce/1.jpg"),
            num: "(23)",
            name: "women party wear dress",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$298",
            prices: "$198",
            price: 198,
            Size: "Size",
            XXL: "XXL",
            bg: "Color :",
            colors: "Red color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
        {
            id: "11",
            src: require("../assets/img/ecommerce/3.jpg"),
            num: "(29)",
            name: "simple white Chair",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$2,999",
            prices: "$2,499",
            price: 2499,
            Size: "Size",
            XXL: "XXL",
            bg: "Color :",
            colors: "Red color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
        {
            id: "12",
            src: require("../assets/img/ecommerce/7.jpg"),
            num: "(20)",
            name: "smooth and soft Kids wear",
            text: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor ipsum quia saepe esse.",
            disc: "$3,498",
            prices: "$2,999",
            price: 2999,
            Size: "Size",
            XXL: "XXL",
            bg: "Color :",
            colors: "Red color",
            stock: "In stock",
            stockbg: "success",
            qnty: 2,
        },
    ];
    static productlist2:any=[
        {
            id: "13",
            pic1: require("../assets/img/ecommerce/9.jpg"),
            pic2: require("../assets/img/ecommerce/09.jpg"),
            item: "Glass Flower pot",
            name: "Glass Flower pot",
            qnty: 2,
            src: require("../assets/img/ecommerce/9.jpg"),
            price: "55",
            stock: "In stock",
            stockbg: "success",
            prices: "$55",
            disc: "$59",
        },
        {
            id: "14",
            pic1: require("../assets/img/ecommerce/8.jpg"),
            pic2: require("../assets/img/ecommerce/08.jpg"),
            item: "Mens party wear t-shirt",
            name: "Mens party wear t-shirt",
            qnty: 2,
            src: require("../assets/img/ecommerce/8.jpg"),
            price: "40",
            stock: "In stock",
            stockbg: "success",
            prices: "$40",
            disc: "$59",
        },
        {
            id: '15',
            pic1: require("../assets/img/ecommerce/6.jpg"),
            pic2: require("../assets/img/ecommerce/06.jpg"),
            item: "glass with soil gift item",
            name: "glass with soil gift item",
            qnty: 2,
            src: require("../assets/img/ecommerce/6.jpg"),
            price: "95",
            stock: "In stock",
            stockbg: "success",
            prices: "$95",
            disc: "$59",
        },
        {
            id: "16",
            pic1: require("../assets/img/ecommerce/1.jpg"),
            pic2: require("../assets/img/ecommerce/01.jpg"),
            item: "women party wear dress",
            name: "women party wear dress",
            qnty: 2,
            src: require("../assets/img/ecommerce/1.jpg"),
            price: "80",
            stock: "In stock",
            stockbg: "success",
            prices: "$80",
            disc: "$59",
        },
        {
            id: "17",
            pic1: require("../assets/img/ecommerce/2.jpg"),
            pic2: require("../assets/img/ecommerce/02.jpg"),
            item: "White Ear buds",
            name: "White Ear buds",
            qnty: 2,
            src: require("../assets/img/ecommerce/2.jpg"),
            price: "35",
            stock: "In stock",
            stockbg: "success",
            prices: "$35",
            disc: "$59",
        },
        {
            id: "18",
            pic1: require("../assets/img/ecommerce/3.jpg"),
            pic2: require("../assets/img/ecommerce/03.jpg"),
            item: "simple white Chair",
            name: "simple white Chair",
            qnty: 2,
            src: require("../assets/img/ecommerce/3.jpg"),
            price: "50",
            stock: "In stock",
            stockbg: "success",
            prices: "$50",
            disc: "$59",
        },
        {
            id: "19",
            pic1: require("../assets/img/ecommerce/4.jpg"),
            pic2: require("../assets/img/ecommerce/04.jpg"),
            item: "pink teddy bear",
            name: "pink teddy bear",
            qnty: 2,
            src: require("../assets/img/ecommerce/4.jpg"),
            price: "45",
            stock: "In stock",
            stockbg: "success",
            prices: "$45",
            disc: "$59",
        },
        {
            id: "20",
            pic1: require("../assets/img/ecommerce/5.jpg"),
            pic2: require("../assets/img/ecommerce/05.jpg"),
            item: "Lence Camara",
            name: "Lence Camara",
            qnty: 2,
            src: require("../assets/img/ecommerce/5.jpg"),
            price: "55",
            stock: "In stock",
            stockbg: "success",
            prices: "$55",
            disc: "$59",
        },
        {
            id: "21",
            pic1: require("../assets/img/ecommerce/7.jpg"),
            pic2: require("../assets/img/ecommerce/07.jpg"),
            item: "smooth and soft Kids wear",
            name: "smooth and soft Kids wear",
            qnty: 2,
            src: require("../assets/img/ecommerce/7.jpg"),
            price: "70",
            stock: "In stock",
            stockbg: "success",
            prices: "$70",
            disc: "$59",
        },
        {
            id: "22",
            pic1: require("../assets/img/ecommerce/11.jpg"),
            pic2: require("../assets/img/ecommerce/10.jpg"),
            item: "Branded Alaram clock",
            name: "Branded Alaram clock",
            qnty: 2,
            src: require("../assets/img/ecommerce/11.jpg"),
            price: "80",
            stock: "In stock",
            stockbg: "success",
            prices: "$80",
            disc: "$70",
        },
        {
            id: "23",
            pic1: require("../assets/img/ecommerce/13.jpg"),
            pic2: require("../assets/img/ecommerce/12.jpg"),
            item: "Branded black headset",
            name: "Branded black headset",
            qnty: 2,
            src: require("../assets/img/ecommerce/13.jpg"),
            price: "550",
            stock: "In stock",
            stockbg: "success",
            prices: "$550",
            disc: "$239",
        },
        {
            id: "24",
            pic1: require("../assets/img/ecommerce/14.jpg"),
            pic2: require("../assets/img/ecommerce/15.jpg"),
            item: "Colorful coffee cup",
            name: "Colorful coffee cup",
            qnty: 2,
            src: require("../assets/img/ecommerce/14.jpg"),
            price: "60",
            stock: "In stock",
            stockbg: "success",
            prices: "$60",
            disc: "$49",
        },
    ];
    static Datacard:any = [
        {
          PRODUCT: require('../assets/img/ecommerce/01.jpg'),
          Title: "laborum et dolorum fuga",
          PRICE: 1999,
          Size: "Size",
          XXL: "S",
          bg:"",
          colors:"",
          Quantity: 1 ,
        },
        {
          PRODUCT: require('../assets/img/ecommerce/02.jpg'),
          Title: "laborum et dolorum fuga",
          PRICE: 1027,
          Quantity: 3,
        },
        {
          PRODUCT: require('../assets/img/ecommerce/03.jpg'),
          Title: "laborum et dolorum fuga",
          PRICE: "$1,027",
          Quantity: 4,
        },
        {
          PRODUCT: require('../assets/img/ecommerce/04.jpg'),
          Title: "laborum et dolorum fuga",
          PRICE: "$1,027",
          Quantity: 3,
        },
      
      ];
    static getProductList(){
        return ProductService.productlist;
    }
    static getProductList2(){
        return ProductService.productlist2;
    }
    static getDatacard(){
        return ProductService.Datacard;
    }
    static id:any = ""
    static getidfronShop(id: any){
        this.id =  id
    }

    static returnId(){
        return this.id
    }
    
}
export default ProductService; 